# Generated by Django 6.0.3 on 2026-07-16 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_businesstoken_businessownerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstoken',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_token', to='businesses.business', verbose_name='Negocio asociado'),
        ),
    ]
