# Generated by Django 6.0.3 on 2026-07-13 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_businessorder_restructure_orderitem'),
        ('pricing', '0002_seed_rings_and_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessorder',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Comisión admin'),
        ),
        migrations.AddField(
            model_name='businessorder',
            name='business_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='A pagar al negocio'),
        ),
        migrations.AddField(
            model_name='businessorder',
            name='is_paid_to_business',
            field=models.BooleanField(default=False, verbose_name='Pagado al negocio'),
        ),
        migrations.AddField(
            model_name='businessorder',
            name='paid_to_business_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='holiday_applied',
            field=models.BooleanField(default=False, verbose_name='Recargo feriado aplicado'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivery_paid',
            field=models.BooleanField(default=False, verbose_name='Envío pagado al repartidor'),
        ),
        migrations.AddField(
            model_name='order',
            name='night_applied',
            field=models.BooleanField(default=False, verbose_name='Recargo nocturno aplicado'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('qr', 'QR'), ('efectivo', 'Efectivo')], default='efectivo', max_length=10, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='rain_applied',
            field=models.BooleanField(default=False, verbose_name='Recargo lluvia aplicado'),
        ),
        migrations.AddField(
            model_name='order',
            name='ring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pricing.shippingring', verbose_name='Anillo de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo de envío'),
        ),
    ]
