# Generated by Django 6.0.3 on 2026-06-09 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Carnet de Identidad')),
                ('drivers_license', models.CharField(max_length=50, verbose_name='Permiso de conducir')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Placa de moto')),
                ('has_ruat', models.BooleanField(default=False, verbose_name='Tiene RUAT')),
                ('bank_qr_image', models.ImageField(blank=True, null=True, upload_to='deliveries/qr/', verbose_name='QR Bancario')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('fuera_servicio', 'Fuera de servicio')], default='fuera_servicio', max_length=20, verbose_name='Estado actual')),
                ('shift_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Turno iniciado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil Delivery',
                'verbose_name_plural': 'Perfiles Delivery',
            },
        ),
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Código de registro',
                'verbose_name_plural': 'Códigos de registro',
                'ordering': ['-created_at'],
            },
        ),
    ]
