# Generated by Django 6.0.3 on 2026-07-13 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rainy_day', models.BooleanField(default=False, verbose_name='Hoy es día lluvioso')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='Hoy es feriado')),
                ('rain_surcharge', models.DecimalField(decimal_places=2, default=2, max_digits=6, verbose_name='Recargo por lluvia (Bs.)')),
                ('holiday_surcharge', models.DecimalField(decimal_places=2, default=2, max_digits=6, verbose_name='Recargo por feriado (Bs.)')),
                ('night_surcharge', models.DecimalField(decimal_places=2, default=4, max_digits=6, verbose_name='Recargo nocturno (Bs.)')),
                ('night_start', models.TimeField(default=datetime.time(23, 59), verbose_name='Inicio horario nocturno')),
                ('night_end', models.TimeField(default=datetime.time(6, 0), verbose_name='Fin horario nocturno')),
                ('admin_qr_image', models.ImageField(blank=True, null=True, upload_to='pricing/qr/', verbose_name='QR de pago del admin')),
                ('admin_commission_pct', models.DecimalField(decimal_places=2, default=12, max_digits=5, verbose_name='Comisión admin sobre venta (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de envío',
                'verbose_name_plural': 'Configuración de envío',
            },
        ),
        migrations.CreateModel(
            name='ShippingRing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Anillo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio (Bs.)')),
            ],
            options={
                'verbose_name': 'Anillo de envío',
                'verbose_name_plural': 'Anillos de envío',
                'ordering': ['number'],
            },
        ),
    ]
